
[functions.google-oauth-authorize]
enabled = true
verify_jwt = false
import_map = "./functions/google-oauth-authorize/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/google-oauth-authorize/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/google-oauth-authorize/*.html" ]

[functions.google-oauth-callback]
enabled = true
verify_jwt = false
import_map = "./functions/google-oauth-callback/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/google-oauth-callback/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/google-oauth-callback/*.html" ]

[functions.google-discover]
enabled = true
verify_jwt = true
entrypoint = "./functions/google-discover/index.ts"
